name: 'Cancel All Previous Workflow Actions'
description: 'This Action will cancel any previous runs that are not `completed` for a given workflow.'
author: styfle
branding:
  icon: 'stop-circle'
  color: 'red'
inputs:
  workflow_id:
    description: 'A single Workflow ID or a comma separated list of IDs'
    required: true
  access_token:
    description: 'Your GitHub Access Token, ie: secrets.GITHUB_TOKEN'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
